### ISSUE TITLE
Local build sometimes does not update .rst files

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/atomistic-cookbook#3]
Sometimes the file `docs/src/examples/mlp_models/linear_model.rst` is not updated using `tox -e docs` and I have to delete it manually (`rm -r  docs/src/examples/`)

**Comment by Luthaf** [comment]
Is this still a valid issue? I'd think that the move to `nox` should have fixed it.

**Comment by agoscinski** [comment]
I think this is a sphinx-gallery issue rather than tox. It only rebuilds examples when it detects changes in the file. Sometimes it does not detect it. I don't think this has a fix for general changes, and I don't give any information about the concrete changes that caused this. There is a `clean_build` command provided in this repo, so people can clean the build folder. That should be good enough.
