### ISSUE TITLE
lode_linear example does not build

### ISSUE THREAD

**Issue by Luthaf** [lab-cosmo/atomistic-cookbook#32]
See build log here: https://github.com/lab-cosmo/software-cookbook/actions/runs/7654053666/job/20857231817?pr=31

This seems to be hitting an issue we fixed on metatensor/rascaline.

Ping @PicoCentauri and @agoscinski, since you wrote the example could you try to fix it?

**Comment by Luthaf** [comment]
As a side note, we should have a cron build job on this repo, checking the build every week.

**Comment by agoscinski** [comment]
Sure, I will give it a look. Maybe I cannot make it today, then I do it next week.

**Comment by PicoCentauri** [comment]
Yes after the retreat I can also check it.
