### ISSUE TITLE
Let users download the `environment.yml` files that correspond to the given examples

### ISSUE THREAD

**Issue by jwa7** [lab-cosmo/atomistic-cookbook#42]

**Comment by PicoCentauri** [comment]
I just had the same idea yesterday. I will set up something today. I would do another box at the end of each tutiorial.

<img width="791" alt="Screenshot 2024-03-26 at 11 57 14" src="https://github.com/lab-cosmo/software-cookbook/assets/15192133/262aecf6-d44b-4f31-89ed-9ee57742c6a9">
