### ISSUE TITLE
Comment bot for downloading the documentation seems to be broken

### ISSUE THREAD

**Issue by PicoCentauri** [lab-cosmo/atomistic-cookbook#45]
Most likely since I changed something in the CI building of the docs #39 the comment bot who posts a link for downloading in the comments of each PR 

https://github.com/lab-cosmo/software-cookbook/blob/3a073a0c2c8ead4bde227652b2a2f87d86eafb0f/.github/workflows/comment-docs-download.yml#L1-L5

We should try to get this running again.

**Comment by Luthaf** [comment]
Looks like the job is considered by Actions, but skipped, so this might be just a configuration issue: https://github.com/lab-cosmo/software-cookbook/actions/runs/8435511200/job/23101075577
