### ISSUE TITLE
Tox changed with nox is not documented

### ISSUE THREAD

**Issue by DavideTisi** [lab-cosmo/atomistic-cookbook#50]
in the commit 0735685bc09803c7bb802b4e34a5dbb64e06d6d5 `tox` has been changed to `nox`. Now using `tox` does not work anymore (of course). This is not documented in the [contributing guidelines](https://github.com/lab-cosmo/software-cookbook/blob/main/CONTRIBUTING.rst). 
I am new to `nox` and what you did, what are the available commands?

**Comment by DavideTisi** [comment]
@PicoCentauri @Luthaf, I tag you two since you were the ones doing this yesterday for what i understand

**Comment by DavideTisi** [comment]
also it is only for me or building with `nox` is quite slower than be before with `tox`. This is not a critic just to notice

**Comment by Luthaf** [comment]
Yes, this was a bit rushed so we could use it yesterday, I'll update the docs!

**Comment by Luthaf** [comment]
> also it is only for me or building with nox is quite slower than be before with tox. This is not a critic just to notice

It should be roughly equivalent. The first build is quite slow in both since we need to create a new conda env and install everything inside; but subsequent builds should be a lot faster in both cases.

**Comment by DavideTisi** [comment]
> > also it is only for me or building with nox is quite slower than be before with tox. This is not a critic just to notice
> 
> It should be roughly equivalent. The first build is quite slow in both since we need to create a new conda env and install everything inside; but subsequent builds should be a lot faster in both cases.

ok, it was of course my first build
