### ISSUE TITLE
when I try to build on my machine the cp2k example cannot be build

### ISSUE THREAD

**Issue by DavideTisi** [lab-cosmo/atomistic-cookbook#51]
The problem seems to be the installation of cp2k

@PicoCentauri

**Comment by DavideTisi** [comment]
this are the output 

> (base) davidetisi@cnr-usbc-calanca:~/Documents/Work/Software/software-cookbook$ nox --session batch-cp2k
> nox > Running session batch-cp2k
> nox > Re-using existing conda env at .nox/batch-cp2k.
> nox > python generate-gallery.py examples/batch-cp2k
> ==> Downloading https://formulae.brew.sh/api/formula.jws.json
> 
> ==> Downloading https://formulae.brew.sh/api/cask.jws.json
> 
> ==> Downloading https://ghcr.io/v2/homebrew/core/cp2k/manifests/2024.1-1
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/d57051e5c04d0b3097e37fd32f277601b9f14ee4bb2aa14cf44d4b9d1a5792da--cp2k-2024.1-1.bottle_manifest.json
> ==> Fetching dependencies for cp2k: gmp, isl, mpfr, libmpc, lz4, xz, zstd, gcc, hwloc, ca-certificates, openssl@3, libevent, pmix, open-mpi, fftw, libxc, openblas and scalapack
> ==> Downloading https://ghcr.io/v2/homebrew/core/gmp/manifests/6.3.0
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/70a72a71216843d66a953c06ff6337445ce9bc94fae9f0e301e2f59005274a8e--gmp-6.3.0.bottle_manifest.json
> ==> Fetching gmp
> ==> Downloading https://ghcr.io/v2/homebrew/core/gmp/blobs/sha256:e8410d92339535174e9f4a5eccc403301b70c7287f2f9a87f06
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/8d39e3597db85ea2b4532e0057381937ab6ed92a64a1728c68e57bc6b3aeef95--gmp--6.3.0.sonoma.bottle.tar.gz
> ==> Downloading https://ghcr.io/v2/homebrew/core/isl/manifests/0.26
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/ec0bbec77171645273dd59a9ccfdf290deccd999b3ca2082e0478d282b777ec0--isl-0.26.bottle_manifest.json
> ==> Fetching isl
> ==> Downloading https://ghcr.io/v2/homebrew/core/isl/blobs/sha256:879bd3d644e9a8a8b43b771de24d56999faf6ab47d961a316cc
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/3df3e17d829f760df141731f0b6f89877308569400c97ab4aed960b8b362dd0d--isl--0.26.sonoma.bottle.tar.gz
> ==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/manifests/4.2.1
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/a2a3424f4974f6febfa0334a93f35f508eaef3f4ad04320f73d9498302295635--mpfr-4.2.1.bottle_manifest.json
> ==> Fetching mpfr
> ==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/blobs/sha256:af35898aedfbb852d0ff927c1c60bf3676c2c29c61408f9714
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/c674606603b100033a0070eaf50fc9d2b76ffddbc995172f54afd4df05452490--mpfr--4.2.1.sonoma.bottle.tar.gz
> ==> Downloading https://ghcr.io/v2/homebrew/core/libmpc/manifests/1.3.1
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/fdfa98e0f8bb3ce075cb32776ac2345aa2f89252706c162aecfc841085fa76be--libmpc-1.3.1.bottle_manifest.json
> ==> Fetching libmpc
> ==> Downloading https://ghcr.io/v2/homebrew/core/libmpc/blobs/sha256:504c66775a10810afcaff53506651eafdb6e9c74dd86881e
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/8cfdfdafca8719b8128a82d7e4bca82e64e0eda6c5d51a5822179108a1e96b3f--libmpc--1.3.1.sonoma.bottle.tar.gz
> ==> Downloading https://ghcr.io/v2/homebrew/core/lz4/manifests/1.9.4
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/379e59b981667f9585b33a2ff318769d8edca3ce6fd2e9a67ed291ae3e0cc872--lz4-1.9.4.bottle_manifest.json
> ==> Fetching lz4
> ==> Downloading https://ghcr.io/v2/homebrew/core/lz4/blobs/sha256:2bad368b2869db32b1b22cea76a6e65da2f4e599ac8ee327b48
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/1680a080f1b23676038b3a03fad837b0e26a30613730ef93f31f87c7a40bdd7a--lz4--1.9.4.sonoma.bottle.tar.gz
> ==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.6.1
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/bc72ad1aed6fc861afaf3fd0af8266ea2913cb871cfdcbeef0c228afb9826c72--xz-5.6.1.bottle_manifest.json
> ==> Fetching xz
> ==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:81c5be0ee64277bcee76ae2be974d82de050e815a266885f363b
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/8d5f1d4596faff29ed7933e8be90599008f828328cb74348de2b7ee5a024d48d--xz--5.6.1.sonoma.bottle.tar.gz
> ==> Downloading https://ghcr.io/v2/homebrew/core/zstd/manifests/1.5.6
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/29403e0df5404d8aeca0e750ac135ec9ef44fc5eeb6df69170ed602acabf0ffb--zstd-1.5.6.bottle_manifest.json
> ==> Fetching zstd
> ==> Downloading https://ghcr.io/v2/homebrew/core/zstd/blobs/sha256:09953f22fd56bc85e0d7ceac8de7e35ed622f3affe78dd7821
> Already downloaded: /Users/davidetisi/Library/Caches/Homebrew/downloads/506615027bab6259ad3b903339790b62d9b547ab08a5eac6707dc96c24da0c38--zstd--1.5.6.sonoma.bottle.tar.gz
> Error: gcc: the bottle needs the Apple Command Line Tools to be installed.
>   You can install them, if desired, with:
>     xcode-select --install
> 
> If you're feeling brave, you can try to install from source with:
>   brew install --build-from-source gcc
> 
> It is expected behaviour that most formulae will fail to build from source.
> It is expected behaviour that Homebrew will be buggy and slow when building from source.
> Do not create any issues about failures building from source on Homebrew's GitHub repositories.
> Do not create any issues building from source even if you think this message is unrelated.
> Any opened issues will be immediately closed without response.
> Do not ask for help from Homebrew or its maintainers on social media.
> You may ask for help building from source in Homebrew's discussions but are unlikely to receive a response.
> If building from source fails, try to figure out the problem yourself and submit a fix as a pull request.
> We will review it but may or may not accept it.
> 
> ../../examples/batch-cp2k/reference-trajectory.py unexpectedly failed to execute correctly:
> 
>     Traceback (most recent call last):
>       File "/Users/davidetisi/Documents/Work/Software/software-cookbook/examples/batch-cp2k/reference-trajectory.py", line 48, in <module>
>         subprocess.run(["brew", "install", "cp2k"], check=True)
>       File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/subprocess.py", line 571, in run
>         raise CalledProcessError(retcode, process.args,
>     subprocess.CalledProcessError: Command '['brew', 'install', 'cp2k']' returned non-zero exit status 1.
> 
> Traceback (most recent call last):
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/generate-gallery.py", line 70, in <module>
>     sphinx_gallery.gen_gallery.generate_gallery_rst(app)
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_gallery.py", line 581, in generate_gallery_rst
>     ) = generate_dir_rst(
>         ^^^^^^^^^^^^^^^^^
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_rst.py", line 531, in generate_dir_rst
>     intro, title, (t, mem) = generate_file_rst(
>                              ^^^^^^^^^^^^^^^^^^
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_rst.py", line 1203, in generate_file_rst
>     output_blocks, time_elapsed = execute_script(
>                                   ^^^^^^^^^^^^^^^
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_rst.py", line 1108, in execute_script
>     execute_code_block(
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_rst.py", line 983, in execute_code_block
>     except_rst = handle_exception(
>                  ^^^^^^^^^^^^^^^^^
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_rst.py", line 970, in execute_code_block
>     is_last_expr, mem_max = _exec_and_get_memory(
>                             ^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_rst.py", line 818, in _exec_and_get_memory
>     mem_max, _ = gallery_conf["call_memory"](
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_gallery.py", line 244, in call_memory
>     return 0.0, func()
>                 ^^^^^^
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/site-packages/sphinx_gallery/gen_rst.py", line 722, in __call__
>     exec(self.code, self.fake_main.__dict__)
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/examples/batch-cp2k/reference-trajectory.py", line 48, in <module>
>     subprocess.run(["brew", "install", "cp2k"], check=True)
>   File "/Users/davidetisi/Documents/Work/Software/software-cookbook/.nox/batch-cp2k/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['brew', 'install', 'cp2k']' returned non-zero exit status 1.
> nox > Command python generate-gallery.py examples/batch-cp2k failed with exit code 1
> nox > Session batch-cp2k failed.`

**Comment by Luthaf** [comment]
Do you have a working homebrew installation? We are using this to install cp2k on mac, since conda-forge only has a linux version.

**Comment by DavideTisi** [comment]
yes, I have homebrew

**Comment by DavideTisi** [comment]
ok no i understand, it should be a problem with my homebrew

**Comment by DavideTisi** [comment]
I try to fix it

**Comment by DavideTisi** [comment]
thanks @Luthaf, I solved the problem
